language: python
cache: pip
sudo: false
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install coveralls
env:
  - APP_CONFIG_FILE=testing
script: python manage.py tests
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: fUe7HpvG3CmNJg/sisHhCBTjzx18JeQKjaJONZ+TWmLkEcTvOlxYQQJxSRAMExOGhLaliNLuOpnqyitmBvBPuggcogTK/cxRgk7EFw0MWxn7vZuiJiHTQcbPIRQSlwuhomj8q0ABKq1Rc5XKDVuvyvVyY49MwBI2njHcKSAkpkA=
  app:
    master: dartmates-staging
  run:
  - python manage.py db upgrade
