"""empty message

Revision ID: 199674c8eb82
Revises: 1eaf2499403c
Create Date: 2015-05-03 12:10:28.053512

"""

# revision identifiers, used by Alembic.
revision = '199674c8eb82'
down_revision = '1eaf2499403c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('joined_at')

    ### end Alembic commands ###
