"""empty message

Revision ID: 36e92a9c018b
Revises: 4758ea467345
Create Date: 2015-05-06 02:42:39.064090

"""

# revision identifiers, used by Alembic.
revision = '36e92a9c018b'
down_revision = '4758ea467345'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_emailed', sa.DateTime(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_emailed')

    ### end Alembic commands ###
