"""empty message

Revision ID: 462399237b20
Revises: 36e92a9c018b
Create Date: 2015-05-08 00:53:05.631633

"""

# revision identifiers, used by Alembic.
revision = '462399237b20'
down_revision = '36e92a9c018b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=1), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')

    ### end Alembic commands ###
