"""empty message

Revision ID: 4758ea467345
Revises: d7d6ebf628
Create Date: 2015-05-05 21:14:37.261459

"""

# revision identifiers, used by Alembic.
revision = '4758ea467345'
down_revision = 'd7d6ebf628'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_visited', sa.DateTime(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_visited')

    ### end Alembic commands ###
